/*
 * Copyright (c) 2016 Jeremy Thomerson
 * Licensed under the MIT license.
 */

'use strict';

module.exports = {

   'extends': 'eslint:recommended',

   'plugins': [
      'silvermine',
   ],

   'rules': {

      'silvermine/array-indentation': 'error',
      'silvermine/call-indentation': 'error',
      'silvermine/fluent-chaining': 'error',
      'silvermine/no-multiple-inline-functions': 'error',
      'silvermine/no-multiline-conditionals': 'error',
      'silvermine/no-multiline-var-declarations': 'error',
      'silvermine/indent': [ 'error', 3, { 'VariableDeclaratorOffset': { 'var': 1, 'let': 1, 'const': 3 }, 'SwitchCase': 1 } ],
      'silvermine/empty-object-spacing': 'error',
      'silvermine/empty-array-spacing': 'error',
      'silvermine/uninitialized-last': 'error',

      'comma-dangle': [ 'error', 'never' ],
      'no-unsafe-finally': 'warn',

      'array-callback-return': 'error',
      'block-scoped-var': 'error',
      'complexity': 'error',
      'curly': 'error',
      'default-case': 'error',
      'dot-location': [ 'error', 'property' ],
      'dot-notation': 'error',
      'eqeqeq': 'error',
      'guard-for-in': 'error',
      'no-alert': 'error',
      'no-caller': 'error',
      'no-case-declarations': 'error',
      'no-else-return': 'error',
      'no-empty-function': 'error',
      'no-empty-pattern': 'error',
      'no-eq-null': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-fallthrough': 'error',
      'no-floating-decimal': 'error',
      'no-implicit-coercion': [ 'error', { 'allow': [ '!!' ] } ],
      'no-implicit-globals': 'error',
      'no-implied-eval': 'error',
      'no-iterator': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-loop-func': 'error',
      'no-multi-spaces': 'error',
      'no-multi-str': 'error',
      'no-native-reassign': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-octal': 'error',
      'no-octal-escape': 'error',
      'no-proto': 'error',
      'no-redeclare': 'error',
      'no-return-assign': 'error',
      'no-script-url': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unused-expressions': 'error',
      'no-unused-labels': 'error',
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-escape': 'error',
      'no-void': 'error',
      'no-with': 'error',
      'radix': 'error',
      'vars-on-top': 'error',
      'wrap-iife': 'error',
      'yoda': 'error',

      'strict': 'error',

      'no-catch-shadow': 'error',
      'no-delete-var': 'error',
      'no-label-var': 'error',
      'no-restricted-globals': [ 'error', 'event' ],
      'no-shadow': 'error',
      'no-shadow-restricted-names': 'error',
      'no-undef': 'error',
      'no-undef-init': 'error',
      'no-unused-vars': 'error',
      'no-use-before-define': 'error',

      'callback-return': [ 'error', [ 'callback', 'cb', 'next', 'done' ] ],
      'global-require': 'error',
      'handle-callback-err': 'error',
      'no-new-require': 'error',
      'no-path-concat': 'error',
      'no-process-env': 'error',
      'no-process-exit': 'error',
      'no-sync': 'error',

      'array-bracket-spacing': [ 'error', 'always' ],
      'block-spacing': 'error',
      'brace-style': 'error',
      'camelcase': 'error',
      'comma-spacing': 'error',
      'comma-style': 'error',
      'computed-property-spacing': 'error',
      'consistent-this': [ 'error', 'self' ],
      'eol-last': 'error',
      'key-spacing': 'error',
      'keyword-spacing': [
         'error',
         {
            'overrides': {
               'catch': { 'after': false },
            },
         },
      ],
      'linebreak-style': [ 'error', 'unix' ],
      'lines-around-comment': 'error',
      'max-depth': [ 'error', 4 ],
      'max-len': [
         'error',
         {
            'code': 140,
            'ignoreUrls': true,
         },
      ],
      'max-nested-callbacks': [ 'error', 6 ],
      'max-params': [ 'error', 5 ],
      'max-statements-per-line': 'error',
      'new-cap': [
         'error',
         { 'capIsNewExceptions': [ 'Q' ] },
      ],
      'new-parens': 'error',
      'newline-after-var': 'error',
      'no-array-constructor': 'error',
      'no-bitwise': 'error',
      'no-lonely-if': 'error',
      'no-multiple-empty-lines': [
         'error',
         {
            'max': 2,
            'maxBOF': 0,
            'maxEOF': 0,
         },
      ],
      'no-negated-condition': 'error',
      'no-nested-ternary': 'error',
      'no-new-object': 'error',
      'no-plusplus': [
         'error',
         { 'allowForLoopAfterthoughts': true },
      ],
      'no-restricted-syntax': [
         'error',
         'ArrowFunctionExpression',
         'ClassBody',
         'ClassDeclaration',
         'ClassExpression',
         'DoWhileStatement',
         'DebuggerStatement',
         'EmptyStatement',
         'ExperimentalRestProperty',
         'ExperimentalSpreadProperty',
         'ForInStatement',
         'JSXIdentifier',
         'JSXNamespacedName',
         'JSXMemberExpression',
         'JSXEmptyExpression',
         'JSXExpressionContainer',
         'JSXElement',
         'JSXClosingElement',
         'JSXOpeningElement',
         'JSXAttribute',
         'JSXSpreadAttribute',
         'JSXText',
         'WithStatement',
         'YieldExpression',
      ],
      'no-spaced-func': 'error',
      'no-trailing-spaces': 'error',
      'no-unneeded-ternary': 'error',
      'no-whitespace-before-property': 'error',
      'object-curly-spacing': [ 'error', 'always' ],
      'one-var': [ 'error', 'always' ],
      'one-var-declaration-per-line': 'error',
      'quote-props': [ 'error', 'as-needed', { 'keywords': true, 'unnecessary': false } ],
      'quotes': [ 'error', 'single' ],
      'semi': [ 'error', 'always' ],
      'semi-spacing': 'error',
      'space-before-blocks': 'error',
      'space-before-function-paren': [ 'error', 'never' ],
      'space-in-parens': [ 'error', 'never' ],
      'space-infix-ops': 'error',
      'space-unary-ops': 'error',
      'unicode-bom': 'error',

   },
};
